"""add agent session superseded_by pointer

Revision ID: 538db5c3ec76
Revises: 6a89c9ef8803
Create Date: 2026-08-10 14:39:56.296446

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "538db5c3ec76"
down_revision: str | Sequence[str] | None = "6a89c9ef8803"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("agent_sessions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("superseded_by", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("agent_sessions", schema=None) as batch_op:
        batch_op.drop_column("superseded_by")

    # ### end Alembic commands ###
